import pysam
import matplotlib.pyplot as plt

# ==============================================================================
# Project: NGS Coverage Visualization
# Author: bariskaya-bio
# Description: Generates a coverage plot from a sorted BAM file to visualize
#              sequencing depth across the target genome.
# ==============================================================================

def plot_coverage(bam_path, output_image="coverage_plot.png"):
    """
    Reads a BAM file, calculates depth per position, and saves a coverage plot.
    """
    try:
        # Opening the BAM file
        bamfile = pysam.AlignmentFile(bam_path, "rb")

        # Calculating read depth (nsegments) for each position
        depths = [col.nsegments for col in bamfile.pileup()]

        if not depths:
            print("[ERROR] No coverage data found. Check if the BAM file is empty or indexed.")
            return

        # Statistical Summary
        avg_depth = sum(depths) / len(depths)
        print(f"--- Coverage Statistics ---")
        print(f"Average Read Depth: {avg_depth:.2f}x")

        # Plotting
        plt.figure(figsize=(10, 5))
        plt.plot(depths, color='teal', linewidth=0.5)
        plt.fill_between(range(len(depths)), depths, color='teal', alpha=0.3)
        
        plt.title("Genomic Read Depth (Coverage)", fontsize=14)
        plt.xlabel("Genomic Position", fontsize=12)
        plt.ylabel("Read Count (Depth)", fontsize=12)
        plt.grid(axis='y', linestyle='--', alpha=0.7)
        
        # Save the figure
        plt.savefig(output_image)
        print(f"[SUCCESS] Plot saved as '{output_image}'.")

    except Exception as e:
        print(f"[ERROR] An unexpected error occurred: {e}")

if __name__ == "__main__":
    # Point to the sorted BAM file generated by the pipeline
    plot_coverage("analysis_results/alignment_sorted.bam")
